name: Test SonarCloud Connection

on:
  workflow_dispatch:  # manual trigger

jobs:
  test-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Test SonarCloud connection
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          organization: RADhaigude
          projectKey: RADhaigude-react-projects
          token: ${{ secrets.SONAR_TOKEN }}

